[0.474s] Invoking command in '/home/yunus/ros2_ws/build/custom_messages_pkg': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/yunus/ros2_ws/install/assignment1:/home/yunus/ros2_ws/install/a2:/opt/ros/foxy /usr/bin/cmake /home/yunus/ros2_ws/src/custom_messages_pkg -DCMAKE_INSTALL_PREFIX=/home/yunus/ros2_ws/install/custom_messages_pkg
[0.485s] -- Found ament_cmake: 0.9.11 (/opt/ros/foxy/share/ament_cmake/cmake)
[0.516s] -- Found PythonInterp: /usr/bin/python3 (found suitable version "3.8.10", minimum required is "3") 
[0.516s] -- Using PYTHON_EXECUTABLE: /usr/bin/python3
[0.738s] -- Found ament_lint_auto: 0.9.7 (/opt/ros/foxy/share/ament_lint_auto/cmake)
[0.804s] -- Found geometry_msgs: 2.0.5 (/opt/ros/foxy/share/geometry_msgs/cmake)
[0.833s] -- Using all available rosidl_typesupport_c: rosidl_typesupport_fastrtps_c;rosidl_typesupport_introspection_c
[0.837s] -- Found rosidl_adapter: 1.3.0 (/opt/ros/foxy/share/rosidl_adapter/cmake)
[0.959s] -- Using all available rosidl_typesupport_cpp: rosidl_typesupport_fastrtps_cpp;rosidl_typesupport_introspection_cpp
[1.056s] -- Found rosidl_default_generators: 1.0.1 (/opt/ros/foxy/share/rosidl_default_generators/cmake)
[1.102s] -- Found PythonInterp: /usr/bin/python3 (found version "3.8.10") 
[1.260s] CMake Error at /opt/ros/foxy/share/rosidl_adapter/cmake/rosidl_adapt_interfaces.cmake:60 (message):
[1.260s]   execute_process(/usr/bin/python3 -m rosidl_adapter --package-name
[1.260s]   custom_messages_pkg --arguments-file
[1.261s]   /home/yunus/ros2_ws/build/custom_messages_pkg/rosidl_adapter__arguments__custom_messages_pkg.json
[1.261s]   --output-dir
[1.261s]   /home/yunus/ros2_ws/build/custom_messages_pkg/rosidl_adapter/custom_messages_pkg
[1.261s]   --output-file
[1.261s]   /home/yunus/ros2_ws/build/custom_messages_pkg/rosidl_adapter/custom_messages_pkg.idls)
[1.261s]   returned error code 1:
[1.261s] 
[1.261s]   Error processing 'float64 commands[]' of
[1.261s]   'custom_messages_pkg/CustomControl': ''commands[]' is an invalid field
[1.261s]   name.  It should have the pattern '^(?!.*__)(?!.*_$)[a-z][a-z0-9_]*$''
[1.261s] 
[1.261s]   Traceback (most recent call last):
[1.261s] 
[1.261s]     File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[1.261s]       return _run_code(code, main_globals, None,
[1.261s]     File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
[1.262s]       exec(code, run_globals)
[1.262s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
[1.262s]       sys.exit(main())
[1.262s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/main.py", line 53, in main
[1.262s]       abs_idl_file = convert_to_idl(
[1.262s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
[1.262s]       return convert_msg_to_idl(
[1.262s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
[1.262s]       msg = parse_message_string(package_name, input_file.stem, content)
[1.262s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 515, in parse_message_string
[1.262s]       fields.append(Field(
[1.262s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 353, in __init__
[1.262s]       raise NameError(
[1.262s] 
[1.262s]   NameError: 'commands[]' is an invalid field name.  It should have the
[1.262s]   pattern '^(?!.*__)(?!.*_$)[a-z][a-z0-9_]*$'
[1.262s] 
[1.263s]   Error in sys.excepthook:
[1.263s] 
[1.263s]   Traceback (most recent call last):
[1.263s] 
[1.263s]     File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 72, in apport_excepthook
[1.263s]       from apport.fileutils import likely_packaged, get_recent_crashes
[1.263s]     File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
[1.263s]       from apport.report import Report
[1.263s]     File "/usr/lib/python3/dist-packages/apport/report.py", line 32, in <module>
[1.263s]       import apport.fileutils
[1.263s]     File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 12, in <module>
[1.264s]       import os, glob, subprocess, os.path, time, pwd, sys, requests_unixsocket
[1.264s]     File "/usr/lib/python3/dist-packages/requests_unixsocket/__init__.py", line 1, in <module>
[1.264s]       import requests
[1.264s]     File "/usr/lib/python3/dist-packages/requests/__init__.py", line 95, in <module>
[1.264s]       from urllib3.contrib import pyopenssl
[1.264s]     File "/usr/lib/python3/dist-packages/urllib3/contrib/pyopenssl.py", line 46, in <module>
[1.264s]       import OpenSSL.SSL
[1.264s]     File "/usr/lib/python3/dist-packages/OpenSSL/__init__.py", line 8, in <module>
[1.264s]       from OpenSSL import crypto, SSL
[1.264s]     File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1553, in <module>
[1.264s]       class X509StoreFlags(object):
[1.265s]     File "/usr/lib/python3/dist-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
[1.265s]       CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
[1.265s] 
[1.265s]   AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
[1.265s] 
[1.265s]   
[1.265s] 
[1.265s]   Original exception was:
[1.265s] 
[1.265s]   Traceback (most recent call last):
[1.265s] 
[1.265s]     File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
[1.265s]       return _run_code(code, main_globals, None,
[1.265s]     File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
[1.265s]       exec(code, run_globals)
[1.265s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/__main__.py", line 19, in <module>
[1.266s]       sys.exit(main())
[1.266s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/main.py", line 53, in main
[1.266s]       abs_idl_file = convert_to_idl(
[1.266s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/__init__.py", line 19, in convert_to_idl
[1.266s]       return convert_msg_to_idl(
[1.266s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/msg/__init__.py", line 28, in convert_msg_to_idl
[1.266s]       msg = parse_message_string(package_name, input_file.stem, content)
[1.266s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 515, in parse_message_string
[1.266s]       fields.append(Field(
[1.266s]     File "/opt/ros/foxy/lib/python3.8/site-packages/rosidl_adapter/parser.py", line 353, in __init__
[1.266s]       raise NameError(
[1.266s] 
[1.266s]   NameError: 'commands[]' is an invalid field name.  It should have the
[1.266s]   pattern '^(?!.*__)(?!.*_$)[a-z][a-z0-9_]*$'
[1.266s] 
[1.266s] Call Stack (most recent call first):
[1.267s]   /opt/ros/foxy/share/rosidl_cmake/cmake/rosidl_generate_interfaces.cmake:130 (rosidl_adapt_interfaces)
[1.267s]   CMakeLists.txt:38 (rosidl_generate_interfaces)
[1.267s] 
[1.267s] 
[1.267s] -- Configuring incomplete, errors occurred!
[1.268s] See also "/home/yunus/ros2_ws/build/custom_messages_pkg/CMakeFiles/CMakeOutput.log".
[1.268s] Invoked command in '/home/yunus/ros2_ws/build/custom_messages_pkg' returned '1': CMAKE_PREFIX_PATH=${CMAKE_PREFIX_PATH}:/home/yunus/ros2_ws/install/assignment1:/home/yunus/ros2_ws/install/a2:/opt/ros/foxy /usr/bin/cmake /home/yunus/ros2_ws/src/custom_messages_pkg -DCMAKE_INSTALL_PREFIX=/home/yunus/ros2_ws/install/custom_messages_pkg
